server:
  port: 8888

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/eadarak00/config-repo
          clone-on-start: true
          default-label: main  # ou 'master' selon votre branche par défaut
          force-pull: true  # s'assure d'avoir les dernières modifications

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka