server:
  port: 9001

spring:
  application:
    name: ms-classe

  config:
    import: "configserver:http://localhost:8888"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.cloud.netflix.eureka: INFO
