server:
  port: 8080

spring:
  application:
    name: ms-gateway

  config:
    import: "configserver:http://localhost:8888"  # préciser explicitement l’URL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
